テスト項目の修正
shinonome-inc/project_finaltask pull request #13
Opened 2022-08-11 12:24 UTC by MiyuSato

2022-08-12 06:07 UTC, MiyuSato commented
2. FeedPageでスクロールをした時キーボードが隠れるように修正しました。
[6f6138f](https://github.com/shinonome-inc/project_finaltask/pull/13/commits/6f6138ff84a104e88b4116c22a7bd18f9fc64a4a)

2022-08-12 06:07 UTC, MiyuSato commented
3. FeedPageで検索フィールドに×ボタンを付けました。
・パッケージを使う方針に変えました。
[89bf921](https://github.com/shinonome-inc/project_finaltask/pull/13/commits/89bf9213d5ac91231c062708d74849ea9739cc10)

2022-08-12 06:08 UTC, MiyuSato commented
4. FeedPageのPull to Refresh を実装しました。
[8d6f116](https://github.com/shinonome-inc/project_finaltask/pull/13/commits/8d6f116ea9aead9293208b1aa58bcc3ad8963cc0)

2022-08-12 06:08 UTC, MiyuSato commented
5. TagPageのページネーションとPull to Refresh を実装しました。
・TagGridViewクラスの新たなファイルを作りました。
[a0672be](https://github.com/shinonome-inc/project_finaltask/pull/13/commits/a0672beeebd1e7e06645cc1d7eb7e95d43eda1cf)

2022-08-13 07:44 UTC, KobayashiYoh requested changes
コメントしました。

2022-08-13 07:44 UTC, KobayashiYoh commented on lib/pages/tag_detail_page.dart
> +                                onRefresh: loadArticle),
TagDetailPageだけCupertinoRefreshIndicatorが表示されないです…。

https://user-images.githubusercontent.com/82624334/184473248-86b59a7e-1473-4db2-be3a-78a3778ca59e.mov

2022-08-13 07:44 UTC, KobayashiYoh commented on lib/views/article_list_view.dart
> +      keyboardDismissBehavior: ScrollViewKeyboardDismissBehavior.onDrag,
スクロールしてもキーボードが閉じないです…。

https://user-images.githubusercontent.com/82624334/184473515-691e9234-dc6e-4661-bb1a-d61b90b91af9.mov

2022-08-13 07:44 UTC, KobayashiYoh commented on lib/views/tag_grid_view.dart
> +                              image: NetworkImage(tag.iconUrl)),
画像の読み込みに失敗しちゃう場合があるので、エラー処理をしてあげるといいかもしれませんね。
修正は任意です。
<img src="https://user-images.githubusercontent.com/82624334/184473749-669c4cb6-cb73-4a2e-8500-e8a57e590cad.png" width="300">

2022-08-13 07:44 UTC, KobayashiYoh commented on lib/views/user_view/user_view.dart
> +                : NotificationListener<ScrollNotification>(
FutureBuilderが無い分この辺の処理がシンプルでいいですね👍

2022-08-13 07:44 UTC, KobayashiYoh commented on lib/views/user_view/user_view.dart
> +                          SliverToBoxAdapter(
他のページもそうなのですが、リロードが上手く機能していないと思われます。

https://user-images.githubusercontent.com/82624334/184473975-fb9522c8-e567-4c15-a98f-cbae98bef163.mov

2022-08-13 07:44 UTC, KobayashiYoh commented on lib/pages/feed_page.dart
> +  }
本当にこれで大丈夫ですか？

https://user-images.githubusercontent.com/82624334/184474229-5bdcf675-b914-46bd-ba79-41274347607c.mov

2022-08-13 22:12 UTC, MiyuSato commented on lib/pages/tag_detail_page.dart
> +                                onRefresh: loadArticle),
https://user-images.githubusercontent.com/83227352/184512964-7156e9d0-bec9-4c5d-aec3-e4b9f513c2f6.mp4

こちらグレーの投稿記事のところを引っ張ることで機能します。グレーの上にCupertinoRefreshIndicatorを乗せようとしてこのような動きになりました。修正した方がよろしいでしょうか。

2022-08-13 22:15 UTC, MiyuSato commented on lib/views/article_list_view.dart
> +      keyboardDismissBehavior: ScrollViewKeyboardDismissBehavior.onDrag,
修正しました！こちら修正後に変更を重ねたために機能しなくなっていました。最終確認を怠ってしまいすみません！

2022-08-13 22:39 UTC, MiyuSato commented on lib/pages/feed_page.dart
> +  }
すみません。こちらはこの機能のことでしょうか。
![image](https://user-images.githubusercontent.com/83227352/184515418-526a3c64-422a-4320-bcaf-e15edc30f836.png)

2022-08-13 22:44 UTC, MiyuSato commented on lib/pages/feed_page.dart
> +  }
このように機能していたので大丈夫かと思ってしまいました。
https://user-images.githubusercontent.com/83227352/184515597-b7e9effd-5b45-481b-88e9-73429dbac62e.mp4
スクロールしてキーボードが消える点とloadArticleについては他のコメントでご指摘いただいき修正いたしました。

2022-08-14 14:57 UTC, MiyuSato commented on lib/views/user_view/user_view.dart
> +                          SliverToBoxAdapter(
![image](https://user-images.githubusercontent.com/83227352/184542742-09f84b6d-fad3-41cf-9694-57f205283103.png)

2022-08-14 15:05 UTC, MiyuSato commented on lib/views/user_view/user_view.dart
> +                          SliverToBoxAdapter(
リロードに関して、各ページのrefreshの機能の修正を行いました。データを再代入するようにしました。
UserPageは以下のような動作をするようになりました。

https://user-images.githubusercontent.com/83227352/184543021-aa997674-f89d-46fc-8150-845b7744f6fe.mp4

2022-08-14 15:11 UTC, MiyuSato commented
[b107f49](https://github.com/shinonome-inc/project_finaltask/pull/13/commits/b107f491a8285402a95a466335d88d52c0e88484)
こちらでキーボードが閉じるようにする修正とtagdetailpage以外の修正を行いました。

2022-08-14 16:02 UTC, MiyuSato commented on lib/views/user_view/user_view.dart
> +                : NotificationListener<ScrollNotification>(
ありがとうございます！Yoさんに教えていただいたおかげです！

2022-08-15 01:02 UTC, MiyuSato commented
[e9ac3f6](https://github.com/shinonome-inc/project_finaltask/pull/13/commits/e9ac3f6c41a4e173dfe3e9446c3055cb0074650e)
こちらでTagDetailPageのListViewとrefreshの修正を行いました。

2022-08-16 05:51 UTC, KobayashiYoh commented on lib/pages/tag_detail_page.dart
> +                                onRefresh: loadArticle),
OKです！

2022-08-16 05:52 UTC, KobayashiYoh commented on lib/views/article_list_view.dart
> +      keyboardDismissBehavior: ScrollViewKeyboardDismissBehavior.onDrag,
OKです！

2022-08-16 05:55 UTC, KobayashiYoh commented on lib/views/tag_grid_view.dart
> +                              image: NetworkImage(tag.iconUrl)),
エラー処理の動作きちんと確認できました。
OKです！

2022-08-16 05:55 UTC, KobayashiYoh commented on lib/views/user_view/user_view.dart
> +                          SliverToBoxAdapter(
しっかり修正できていて素晴らしいです！

2022-08-16 06:05 UTC, KobayashiYoh commented on lib/pages/feed_page.dart
> +  }
すみません。
こちらの勘違いがありました。
この実装で問題ないです。
質問内容も抽象的すぎましたね。
申し訳ございません。

2022-08-16 06:10 UTC, KobayashiYoh approved these changes

2022-08-16 06:11 UTC, KobayashiYoh commented
LGTMです！
二次レビューに進んでください！

2022-08-16 06:14 UTC, KobayashiYoh commented on lib/views/user_view/user_view.dart
> +                          SliverToBoxAdapter(
コメントし忘れていたのですが、記事が二重に取得されるという現象も修正されていますね。

2022-08-17 10:14 UTC, kota78 commented
一次レビューからの修正で実装したい機能はきちんとできていると思います！
一つ質問で、検索フィールドの×ボタンは無くす方針ということでしょうか？

2022-08-17 10:19 UTC, kota78 commented
<img width="547" alt="スクリーンショット 2022-08-17 19 10 51" src="https://user-images.githubusercontent.com/82959924/185094493-474b470d-6dfa-4fb6-8e2a-a7f837d9a7cf.png">

https://user-images.githubusercontent.com/82959924/185094588-e13189c1-43e6-4410-a8b2-d0886aadbc43.mp4

タップした時に色がつく範囲が区切り線で区切られている部分とは違うところになっているようです。
今回の差分ではないですし、あまり重要ではない気もしますが一応記載しておきます。

2022-08-17 12:14 UTC, MiyuSato commented on lib/pages/feed_page.dart
> +            CupertinoSearchTextField(
ありがとうございます。
こちらのパッケージを用いると検索フィールドに文字を入力すると×ボタンが出てきます。

https://user-images.githubusercontent.com/83227352/185115858-6adf5666-6c33-4b6b-a297-a8892e0dd2cb.mp4

2022-08-17 13:18 UTC, MiyuSato commented
> 
ほんとですね！ご指摘ありがとうございます。
こちら修正した方がよろしいでしょうか…？

2022-08-17 14:57 UTC, kota78 commented on lib/pages/feed_page.dart
> +            CupertinoSearchTextField(
失礼いたしました、、
文字を入力すると出てくる仕様なんですね

2022-08-17 14:58 UTC, kota78 commented
個人的には必要ないと思います。違和感があれば直してあげてください😀
それ以外はLGTMです！

2022-08-17 22:48 UTC, MiyuSato commented
かしこまりました！今回はそのまま修正しないで進みたいと思います。

2022-08-17 23:21 UTC, merged