テスト項目の修正#02
shinonome-inc/project_finaltask pull request #14
Opened 2022-08-18 12:42 UTC by MiyuSato

前回の残りの
・FollowPageとFollowerPageのPull to refresh
・UserPageのフォロー数・フォロワー数が0のときタップしても何も起こらないようにする
を実装しました。

2022-08-18 13:36 UTC, KobayashiYoh requested changes
コメントしました。

2022-08-18 13:36 UTC, KobayashiYoh commented on lib/pages/top_page.dart
>                            textAlign: TextAlign.center,
こういう細かい点に自分で気づくことができるのは素晴らしいです👍
自分だったら見落としてしまいそうです。

2022-08-18 13:36 UTC, KobayashiYoh commented on lib/pages/follow_page.dart
> +                            CupertinoSliverRefreshControl(
先ほどDawnでもお話しさせていただきましたが、リストの要素数が少ない場合でもpull to refreshできるようになるといいですね。

2022-08-19 02:33 UTC, KobayashiYoh commented on lib/pages/feed_page.dart
> +                              parent: AlwaysScrollableScrollPhysics()),
なるほど！
こうやって修正することができるんですね。
とても勉強になりました。
ありがとうございます！

2022-08-19 02:35 UTC, KobayashiYoh commented
![image](https://user-images.githubusercontent.com/82624334/185530525-50882201-e604-4077-a38e-253d9efcbf67.png)

2022-08-19 02:35 UTC, KobayashiYoh approved these changes

2022-08-19 04:46 UTC, ShuheiYoshidaJP commented
オッケーです。
マージします。

2022-08-19 04:46 UTC, merged