FeedPage Pagenation
shinonome-inc/project_finaltask pull request #5
Opened 2022-03-10 02:24 UTC by MiyuSato

FeedPageの無限スクロールです。articlelistviewのファイル内で作っています。
FeedPageを開いたときの、最初のCircularProgressIndicatorを修正のなかで消してしまったので、どこに入れたら良いのか考え中です。

2022-03-10 04:56 UTC, KobayashiYoh requested changes
4点コメントしました。ご確認よろしくお願いします。

FeedPage関連のプルリクにTagPageの差分まで入ってしまっているため、FeedPageはFeedPageのブランチで、TagPageはTagPageのブランチで作業した方がいいかもしれません。
https://classroom.google.com/u/2/c/OTI5NzEwNDk2OTBa/m/NDIyOTMwMTIxMDk4/details?hl=ja

2022-03-10 04:56 UTC, KobayashiYoh commented on lib/pages/articlelistview.dart
> +  late List<Article> _articleList;
一番最初にFeedPageを開いたとき、LateInitializationErrorが発生してしまうので、修正しましょう。
TagPageが参考になるかもしれません。
<img src="https://user-images.githubusercontent.com/82624334/157589211-bc6d5e95-14b1-4112-a725-9c1213d77d7d.png" width="300">

2022-03-10 04:56 UTC, KobayashiYoh commented on lib/pages/articlelistview.dart
> +                  '@${article.user.id} 投稿日:${changeDateFormat(article.date)} LGTM:${article.lgtm.toString()}'),
記事のタイトルは2行以内で収まるように表示しましょう。
詳しくは、最終課題のFigmaを参照してください。
https://www.figma.com/file/r22atGeJ5LpGwOUbYXXOPw/Mobile-Qiita-App?node-id=101%3A25522

2022-03-10 04:56 UTC, KobayashiYoh commented on lib/pages/articlelistview.dart
> +        if (page == 1) {
エミュレータできちんと無限スクロールできました！
コードもシンプルで素晴らしいです！

2022-03-10 04:56 UTC, KobayashiYoh commented on lib/pages/tagdetailpage.dart
> +                    '@${article.user.id} 投稿日:${changeDateFormat(article.date)} LGTM:${article.lgtm.toString()}'),
こちらも記事のタイトルが2行以内で収まるように表示してあげましょう。

2022-03-30 02:41 UTC, MiyuSato commented
LateInitializationErrorが消えました。ご指摘いただいた記事のタイトルを2行以内に収める修正を行いました。
TagPageのブランチで作業してしまいました。

2022-03-30 04:32 UTC, KobayashiYoh commented
よく修正できています！
僕はLGTMなので二次レビューの依頼を出してください。

2022-03-31 05:32 UTC, Yoshida-koshi commented on lib/pages/articlelistview.dart
> +              border: Border(
細かいところだけど、Figma通りにしてください！

![#02 Feed Page - loading](https://user-images.githubusercontent.com/85224998/160982889-a7562f7f-65a8-4837-875b-d26fdab657c6.png)

2022-03-31 05:34 UTC, Yoshida-koshi commented
何回かページネーションすると下のようなエラーが吐かれてしまうので、修正してください！

<img width="1512" alt="スクリーンショット 2022-03-31 14 30 10" src="https://user-images.githubusercontent.com/85224998/160983541-329fc589-2c13-4ca8-ace9-f3a394abd00e.png">

2022-04-13 13:32 UTC, Yoshida-koshi commented on lib/pages/articlelistview.dart
> +              border: Border(
OKです！

2022-04-13 13:41 UTC, Yoshida-koshi commented
ページネーションでエラーが出なくなったのは素晴らしいです！あともう一つだけ修正してほしい所があるので修正してください！
投稿記事の投稿日が12日が先に出ていて、その後に13日が出ているので修正お願いします！

<img width="1512" alt="スクリーンショット 2022-04-13 22 35 51" src="https://user-images.githubusercontent.com/85224998/163193552-831ba177-e37f-43b4-8cd8-c44652a967b6.png">

2022-04-20 02:45 UTC, MiyuSato commented
_isLoadingのtrueとfalseの修正を数か所で行い、page++;のタイミングを変更しました。最後に変更したのがpage++;だったので、この変更が決め手となったと思っています。

2022-04-22 09:12 UTC, Yoshida-koshi commented
_isLoadingをtrueにするタイミングを修正できていて素晴らしいです！LGTMです！

2022-04-22 09:13 UTC, Yoshida-koshi approved these changes

2022-04-22 09:13 UTC, merged