Mypage ログインとUIの実装
shinonome-inc/project_finaltask pull request #7
Opened 2022-06-29 15:06 UTC by MiyuSato

ログイン全般とMyPageのUIの実装をしました。
ログインに関してはloginpageとtoppageで行っています。
ログインしたあとの状態を確認するためMyPageを実装しました。
AppBarに影を付けたり、アイコンをFigmaのものにより近いものに変えたりと、他のページのUIの細かな修正も行いました。無限スクロールのコードで冗長なところがあったので少し修正しました。

できていないこと
・ログイン後にMyPageを開くと、一度ログインするページが描画されてからログイン状態のMyPageが表示される。
・loginPageの角丸

上の2点はまだ解決できていないところです。一度できているところまででプルリクエストをしたほうが良いのではないかと思って今に至ります。
プルリクエストのタイミングがつかめず、前回からコードがたくさん増えてしまって読みづらくて申し訳ないです。今回主に行ったことはログイン機能の実装です。

2022-06-30 10:49 UTC, Yoshida-koshi commented
案件に入ると必ず言われるのですが、PullRequestを出すときに実装した後の様子を動画にしてもらうと助かります！
理由としてはPullRequestを見るだけで、Miyuさんの環境ではしっかりと動いていることが確認できるからです。

2022-06-30 10:54 UTC, Yoshida-koshi commented
許可するボタンを押してもそれ以降何も反応がありませんでしたが、そちらの環境では動きますでしょうか？

![Simulator Screen Shot - iPhone 11 Pro Max - 2022-06-30 at 19 51 24](https://user-images.githubusercontent.com/85224998/176659964-5669613c-15bb-40c6-9d21-e904dd361090.png)

2022-06-30 11:28 UTC, Yoshida-koshi reviewed
コメントしました〜

2022-06-30 11:28 UTC, Yoshida-koshi commented on lib/pages/loginpage.dart
> +                .contains('https://qiita.com/settings/applications?code')) {
61行目で指定したURLが同じなので1つにまとめられそうですね。

2022-06-30 11:28 UTC, Yoshida-koshi commented on lib/pages/mypage.dart
> +          Row(
左の余白が他のTextよりも多いですね。FigmaのUI通りに実装してください。
![Simulator Screen Shot - iPhone 11 Pro Max - 2022-06-30 at 20 21 57](https://user-images.githubusercontent.com/85224998/176665644-39cad577-facc-473a-b728-72e0f9bd5a5a.png)

2022-06-30 11:28 UTC, Yoshida-koshi commented on lib/pages/mypage.dart
> +              ? Column(
98行目でNotLoginViewクラスを定義しているので、loginViewクラスを定義した方がコードが見やすくなっていいと思います。

2022-06-30 11:31 UTC, Yoshida-koshi commented
基本的にブランチ名で書いているページ以外はこのブランチで作業するのはやめた方がいいと思います！理由としてはコードレビューする範囲が広すぎるので、レビュワーがレビューするのがとても大変ですし、質も下がってしまうからです。

2022-07-05 05:33 UTC, MiyuSato commented
> 案件に入ると必ず言われるのですが、PullRequestを出すときに実装した後の様子を動画にしてもらうと助かります！ 理由としてはPullRequestを見るだけで、Miyuさんの環境ではしっかりと動いていることが確認できるからです。



> かしこまりました。動画もつけます！

2022-07-05 05:35 UTC, MiyuSato commented
> 案件に入ると必ず言われるのですが、PullRequestを出すときに実装した後の様子を動画にしてもらうと助かります！ 理由としてはPullRequestを見るだけで、Miyuさんの環境ではしっかりと動いていることが確認できるからです。

かしこまりました。動画もつけます！

2022-07-05 05:36 UTC, MiyuSato commented on lib/pages/mypage.dart
> +          Row(
修正しました

2022-07-05 05:44 UTC, MiyuSato commented on lib/pages/mypage.dart
> +              ? Column(
なるほどです！loginViewクラスに切り離します

2022-07-05 06:21 UTC, MiyuSato commented
> 基本的にブランチ名で書いているページ以外はこのブランチで作業するのはやめた方がいいと思います！理由としてはコードレビューする範囲が広すぎるので、レビュワーがレビューするのがとても大変ですし、質も下がってしまうからです。

そうですよね、、気を付けていきます！
今回ですと、ログインの実装のブランチで作業を行ってプリクエストを出したあと、MyPageのブランチを新たに作成して実装を進めていくのがよろしかったでしょうか。それともさらに細かく段階を踏んだ方がよろしいでしょうか。

2022-07-05 06:47 UTC, MiyuSato commented
> > 基本的にブランチ名で書いているページ以外はこのブランチで作業するのはやめた方がいいと思います！理由としてはコードレビューする範囲が広すぎるので、レビュワーがレビューするのがとても大変ですし、質も下がってしまうからです。
> 
> そうですよね、、気を付けていきます！ 今回ですと、ログインの実装のブランチで作業を行ってプリクエストを出したあと、MyPageのブランチを新たに作成して実装を進めていくのがよろしかったでしょうか。それともさらに細かく段階を踏んだ方がよろしいでしょうか。

ブランチについてもう一つ質問させてください。今のコードですとログイン状態が保持されてしまっていているので、ログイン直後のWebviewのnavigationdelegateが機能しているのか確認するのが難しいです。そのためログアウトボタンをsettingpageに簡易的に作ろうと思うのですが、その場合ブランチを新しく作った方がよろしいでしょうか。

2022-07-05 06:51 UTC, MiyuSato commented on lib/pages/mypage.dart
> +          Row(
修正しました
mypageのディレクトリに、遷移を行うmypageとloginviewとnot_loginviewを置きました！

2022-07-05 06:56 UTC, MiyuSato commented on lib/pages/loginpage.dart
> +                .contains('https://qiita.com/settings/applications?code')) {
修正しましたが動作確認ができていないので、下に書いてあるブランチの質問を読んでいただけるとありがたいです。

2022-07-05 06:57 UTC, MiyuSato commented on lib/pages/mypage.dart
> +              ? Column(
なるほどです！loginViewクラスに切り離します
mypageのディレクトリに、遷移を行うmypageとloginviewとnot_loginviewを置きました！

2022-07-08 08:39 UTC, Yoshida-koshi commented
> 今回ですと、ログインの実装のブランチで作業を行ってプリクエストを出したあと、MyPageのブランチを新たに作成して実装を進めていくのがよろしかったでしょうか。それともさらに細かく段階を踏んだ方がよろしいでしょうか。

今回はログインページのUIで１つ、ログイン認証で１つ、MyPageのUIで１つのPullRequestを提出するといいと思います！なので実装すする順番はログインページのUI -> ログイン認証 -> MyPageのUIって感じですね！

2022-07-08 09:08 UTC, Yoshida-koshi commented
> ブランチについてもう一つ質問させてください。今のコードですとログイン状態が保持されてしまっていているので、ログイン直後のWebviewのnavigationdelegateが機能しているのか確認するのが難しいです。そのためログアウトボタンをsettingpageに簡易的に作ろうと思うのですが、その場合ブランチを新しく作った方がよろしいでしょうか。

ログアウトボタンを作らなくても、ログイン状態を消すことができます！
検証しているOSはiOSですか？
OSによって、ログイン状態を消す方法が違うので教えて頂きたいです！

2022-07-08 09:27 UTC, Yoshida-koshi commented on lib/pages/loginpage.dart
> +                .contains('https://qiita.com/settings/applications?code')) {
僕の方で検証しましたが、「許可する」ボタンを押しても、FeedPageに遷移されていないですね。

https://user-images.githubusercontent.com/85224998/177961828-48ddd10c-d3ce-4a08-ba90-6db46356f2a7.mp4

2022-07-08 09:32 UTC, Yoshida-koshi commented on lib/pages/mypage.dart
> +              ? Column(
OKです！

2022-07-09 02:22 UTC, MiyuSato commented on lib/pages/loginpage.dart
> +                .contains('https://qiita.com/settings/applications?code')) {
本当ですね！遷移されていないですね。私のほうでは現在このように動作しています。

https://user-images.githubusercontent.com/83227352/178087989-295dc4ca-725d-44fb-88ed-909d9acfe755.mp4

2022-07-09 02:27 UTC, MiyuSato commented
> > 今回ですと、ログインの実装のブランチで作業を行ってプリクエストを出したあと、MyPageのブランチを新たに作成して実装を進めていくのがよろしかったでしょうか。それともさらに細かく段階を踏んだ方がよろしいでしょうか。
> 
> 今回はログインページのUIで１つ、ログイン認証で１つ、MyPageのUIで１つのPullRequestを提出するといいと思います！なので実装すする順番はログインページのUI -> ログイン認証 -> MyPageのUIって感じですね！

なるほど！UIと機能で分けるのですね！ありがとうございます

2022-07-09 02:33 UTC, MiyuSato commented
> 

ログイン状態消せるのですね！Androidで検証してます。

2022-07-09 06:29 UTC, KobayashiYoh commented on lib/pages/loginpage.dart
> +                .contains('https://qiita.com/settings/applications?code')) {
@Yoshida-koshi 
Koshiさん間違えてQiitaじゃなくてGitHubのアカウントでログインしていませんか？

2022-07-09 06:36 UTC, KobayashiYoh commented on lib/pages/loginpage.dart
> +                .contains('https://qiita.com/settings/applications?code')) {
自分の環境ではFeedPageへ遷移できました。

2022-07-12 15:05 UTC, MiyuSato commented on lib/pages/mypage.dart
> +          Row(
このページにたどり着いたときはどのようにログインを行いましたか？

2022-07-12 22:13 UTC, Yoshida-koshi commented on lib/pages/mypage.dart
> +          Row(
MyPageのUIも確認したかったので、こちらの方で少しコードを変更して、ログインしたらFeedPageに遷移できるようにして、MyPageにたどり着いたって感じですね！

2022-07-13 13:59 UTC, Yoshida-koshi commented
ログイン後にFeedPageに遷移できることは確認できました！

2022-07-13 14:27 UTC, Yoshida-koshi reviewed
基本的に実装が終わったら、いらない部分は削除し、エラーが出たら対処してください。
コメントしました〜

2022-07-13 14:27 UTC, Yoshida-koshi commented on lib/pages/loginpage.dart
> +  bool _hascode = false;
_hascodeは使われていないのでいらないですね。

2022-07-13 14:27 UTC, Yoshida-koshi commented on lib/pages/loginpage.dart
> +import 'package:flutter/cupertino.dart';
今回は全てmaterial.dartが使われているので、cupertino.dartはいらないですね。

2022-07-13 14:27 UTC, Yoshida-koshi commented on lib/pages/loginpage.dart
> +    _sub.cancel();
_subはdisposeしているだけなので、おそらく_subはいらないですね。

<img width="874" alt="スクリーンショット 2022-07-13 23 12 24" src="https://user-images.githubusercontent.com/85224998/178755102-7f701963-f389-4d48-803c-03f6c2f38759.png">

2022-07-16 12:59 UTC, MiyuSato commented
> ログイン後にFeedPageに遷移できることは確認できました！

よかったです！ありがとうございます

2022-07-16 13:09 UTC, MiyuSato commented on lib/pages/loginpage.dart
> +  bool _hascode = false;
削除しました

2022-07-16 13:09 UTC, MiyuSato commented on lib/pages/loginpage.dart
> +import 'package:flutter/cupertino.dart';
こちらも削除しました！

2022-07-16 13:54 UTC, MiyuSato commented on lib/pages/loginpage.dart
> +    _sub.cancel();
こちらも以前利用しようとしていたものだったので、削除しました

2022-07-16 15:08 UTC, Yoshida-koshi commented
LGTMです！2次レビューをお願いしてください。

2022-07-20 02:29 UTC, KobayashiYoh requested changes
コメントしました。
何かわからないことがあれば気軽に質問してください。

2022-07-20 02:29 UTC, KobayashiYoh commented on lib/qiita_client.dart
> +  // 'df9586e167ea06de68a460858b20b6a237d2b3a2'; //登録したアクセストークン
クライアントIDとクライアントシークレットは悪意のある第三者に悪用されるのを防ぐため、必ずgitの管理下から外してください。

アクセストークンも悪用されると困るため、16行目のコメントアウトは必ず削除してください。

2022-07-20 02:29 UTC, KobayashiYoh commented on lib/qiita_client.dart
> +      }),
👍

2022-07-22 14:30 UTC, MiyuSato commented on lib/pages/loginpage.dart
> +  }
![image](https://user-images.githubusercontent.com/83227352/180460767-83b476db-81ba-485f-b716-91e31cb15266.png)
このstateに入れる値を生成しています！

2022-07-22 21:11 UTC, MiyuSato commented on lib/pages/feedpage.dart
> +                return Text('${snapshot.error!}');
ErrorViewを追加しました

2022-07-22 21:11 UTC, MiyuSato commented on lib/pages/mypage/loginview.dart
> +  // final Future<List<Article>> userarticle = QiitaClient().fetchUserArticle();
削除しました

2022-07-22 21:11 UTC, MiyuSato commented on lib/pages/mypage/loginview.dart
> +                ? Center(child: Text('Error'))
ErrorViewを追加しました

2022-07-22 21:12 UTC, MiyuSato commented on lib/pages/mypage/loginview.dart
> +// }
削除しました

2022-07-22 21:12 UTC, MiyuSato commented on lib/pages/tagdetailpage.dart
> +                return Text('${snapshot.error!}');
ErrorViewを追加しました

2022-07-22 21:17 UTC, MiyuSato commented on lib/pages/toppage.dart
> +// }
削除しました

2022-07-24 13:53 UTC, MiyuSato commented on lib/models/user.dart
> +      description: json['description'] ?? '未設定',
ありがとうございます

2022-07-25 04:23 UTC, MiyuSato commented on lib/qiita_client.dart
> +  // 'df9586e167ea06de68a460858b20b6a237d2b3a2'; //登録したアクセストークン
[b5cb78b](https://github.com/shinonome-inc/project_finaltask/pull/7/commits/b5cb78bdf0e9c0b5f38428a78aaabc62d29a31ba)
ここでclientIDとclientSecretをsecret.dartファイルに書いて、secret.dartファイルを.gitignoreに書きました。しかし、ここで差分が見られるということはgitignoreできていないということなのでしょうか。

2022-07-26 12:51 UTC, KobayashiYoh commented on lib/pages/feedpage.dart
> +                return Text('${snapshot.error!}');
OKです👍

2022-07-26 12:53 UTC, KobayashiYoh commented on lib/pages/loginpage.dart
> +  }
なるほど！
教えて下さりありがとうございます！

2022-07-26 12:53 UTC, KobayashiYoh commented on lib/pages/mypage/loginview.dart
> +  // final Future<List<Article>> userarticle = QiitaClient().fetchUserArticle();
OKです👍

2022-07-26 12:53 UTC, KobayashiYoh commented on lib/pages/mypage/loginview.dart
> +                ? Center(child: Text('Error'))
OKです👍

2022-07-26 12:53 UTC, KobayashiYoh commented on lib/pages/mypage/loginview.dart
> +// }
OKです👍

2022-07-26 12:53 UTC, KobayashiYoh commented on lib/pages/tagdetailpage.dart
> +                return Text('${snapshot.error!}');
OKです👍

2022-07-26 12:53 UTC, KobayashiYoh commented on lib/pages/toppage.dart
> +// }
OKです👍

2022-07-26 13:01 UTC, KobayashiYoh commented on lib/qiita_client.dart
> +  // 'df9586e167ea06de68a460858b20b6a237d2b3a2'; //登録したアクセストークン
そうですね。
まだGitの管理下に含まれちゃっていますね。

2022-07-29 09:55 UTC, KobayashiYoh commented on lib/qiita_client.dart
> +  // 'df9586e167ea06de68a460858b20b6a237d2b3a2'; //登録したアクセストークン
しっかり修正できています
OKです

2022-07-29 09:55 UTC, KobayashiYoh commented on lib/qiita_client.dart
> +  // 'df9586e167ea06de68a460858b20b6a237d2b3a2'; //登録したアクセストークン
しっかり修正できています
OKです

2022-07-29 09:55 UTC, KobayashiYoh commented on lib/qiita_client.dart
> +  // 'df9586e167ea06de68a460858b20b6a237d2b3a2'; //登録したアクセストークン
しっかり修正できています
OKです

2022-07-29 09:55 UTC, KobayashiYoh approved these changes

2022-07-29 09:58 UTC, merged

2022-07-29 09:59 UTC, KobayashiYoh commented
LGTMです！
マージしました！